name: Update README all day at 04:03

on:
  schedule:
    - cron: '03 4 * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          npm install
      - name: Update README.md file
        run: |
          node update_readme.js
        env:
          CI: true
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: 'JordBSN'
          author_email: 'jord.bastin@gmail.com'
          message: ':memo: README.md updated by Gabot'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}